# Generated by Django 4.2.3 on 2023-07-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_perfiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="domicilio",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name="perfil",
            table="app_perfiles_perfil",
        ),
    ]
